"use client";

import { AvatarImg } from "@/components/widgets/avatar";
import { PrimaryBtn, SecondaryBtn } from "@/components/btn";
import useAuthUser, { useAuthUserId } from "@/hooks/auth";

import WidgetsPopup from "@/components/widgets/popup";
import Input from "@/components/forms/input";
import FormsPhoneNumber from "@/components/forms/phoneNumber";
import LocationInput from "../../../../components/forms/location";
import TagsInput from "@/components/forms/tags";
import { getUser } from "@/services/user";
import { useEffect, useState } from "react";
import CompleteProfile from "@/components/widgets/profile/completeProfile";
import FormsWebsite from "@/components/forms/website";
import BiographyEditor from "@/components/forms/bio";

// export const metadata = {
//    title: " Emegen",
//    description: "Generated by create next app",
// };

export default function EditProfilePage() {
   const [user, setUser] = useState();
   // authUser?.userName?.replace(/%40/g, "").trim() || ""
   console.clear();
   useEffect(() => {
      Promise.all([useAuthUser()]).then(([user]) => {
         if (!user?.userName) {
            return;
         }
         getUser(user?.userName || "").then((userData) => {
            setUser(userData.data || {});
         });
      });
   }, []);

   console.log("file: edit-profile.jsx:13 => user=>", user);

   return (
      <>
         <main className="flex-1">
            <h1 className="mb-4">Edit profile</h1>
            <section className="main flex flex-col gap-8">
               <div className="main flex flex-col gap-4">
                  <b>Kişisel Bilgiler</b>
                  <div className="flex gap-4">
                     <label>
                        <b className="block">İsim</b>
                        <input
                           className="w-full h-9 px-3 py-2 !bg-transparent border relative border-tertiary shadow shadow-tertiary rounded-2xl outline-none"
                           type="text"
                           defaultValue={user?.name || ""}
                           placeholder="İsminizi girin"
                        />
                     </label>
                     <label>
                        <b className="block">Kullanıcı Adı</b>
                        <input
                           className="w-full h-9 px-3 py-2 !bg-transparent border relative border-tertiary shadow shadow-tertiary rounded-2xl outline-none"
                           type="text"
                           defaultValue={user?.userName || ""}
                           placeholder="Kullanıcı adınızı girin"
                        />
                     </label>
                     <label>
                        <b className="block">Kullanıcı Adı</b>
                        <input
                           className="w-full h-9 px-3 py-2 !bg-transparent border relative border-tertiary shadow shadow-tertiary rounded-2xl outline-none"
                           type="text"
                           defaultValue={user?.userName || ""}
                           placeholder="Kullanıcı adınızı girin"
                        />
                     </label>
                  </div>
                  <SecondaryBtn className="ml-auto">Güncelle</SecondaryBtn>
               </div>
               <div className="main">
                  <b>Konum</b>
                  <LocationInput
                     defaultValue={user?.location || ""}
                     placeholder="Konumunuzu girin"
                     onChange={(e) => {
                        console.log("Location changed:", e);
                     }}
                  />
               </div>
               <div className="main">
                  <b>Etiketler</b>
                  {/* {console.log("user?.tags:", user?.tags)} */}
                  <TagsInput
                     tags={user?.tags}
                     placeholder="İlgi alanlarınızı girin"
                     onChange={(e) => {
                        console.log("Tags changed:", e);
                     }}
                  />
               </div>
               <BiographyEditor defaultValue={user?.bio} />
               <div className="main">
                  <FormsWebsite name="website" value={user?.website} />
                  <FormsWebsite name="linkedin" title="" />
               </div>
            </section>
         </main>
         <aside className="min-w-80 h-min main ">
            <CompleteProfile user={user} />
         </aside>
      </>
   );
}
