import { AvatarImg } from "@/components/widgets/avatar";
import { PrimaryBtn, SecondaryBtn } from "@/components/btn";
import useAuthUser, { useAuthUserId } from "@/hooks/auth";
import ChartsDoughnut from "@/components/charts/doughnut";
import WidgetsPopup from "@/components/widgets/popup";
import Input from "@/components/forms/input";
import FormsPhoneNumber from "@/components/forms/phoneNumber";
import LocationInput from "../../../../components/forms/location";
import TagsInput from "@/components/forms/tags";
import { getUser } from "@/services/user";

// export const metadata = {
//    title: " Emegen",
//    description: "Generated by create next app",
// };

export default async function EditProfilePage() {
   const authUser = await useAuthUser();
   const userToken = await useAuthUserId();
   const { status, data: user } = await getUser(
      authUser?.userName?.replace(/%40/g, "").trim() || ""
   );

   console.log("file: edit-profile.jsx:13 => user=>", user);

   const userField =
      user &&
      Object.entries(user).filter(
         ([key]) =>
            ![
               "_id",
               "active",
               "createdAt",
               "updatedAt",
               "__v",
               "password",
               "email",
               "followersCount",
               "followingCount",
               "isFollowing",
            ].includes(key)
      );

   const userFieldCount = userField.length;

   const validUserFieldCount =
      user &&
      Object.entries(user).filter(
         ([key, val]) =>
            ![
               "_id",
               "active",
               "createdAt",
               "updatedAt",
               "__v",
               "password",
               "email",
               "followersCount",
               "followingCount",
               "isFollowing",
            ].includes(key) && val
      ).length;

   return (
      <section>
         <h1 className="mb-4">Edit profile</h1>
         <section className="flex flex-col lg:flex-row gap-8">
            <main className="flex flex-col gap-8">
               <div className="main flex items-center gap-8">
                  <AvatarImg size={48} />
                  <div className="">
                     <SecondaryBtn>Yeni fotoğraf yükleyin</SecondaryBtn>
                     <p className="whitespace-nowrap">
                        En az 128x128 px önerilir
                     </p>
                     <p className="whitespace-nowrap">
                        JPEG veya PNG'ye izin verilir
                     </p>
                  </div>
               </div>
               <div className="main relative">
                  <WidgetsPopup title="Personal Information">
                     <ul className="flex justify-between gap-4">
                        <li className="min-w-60">
                           {/* <p>Name</p> */}
                           <Input title="İsim" value={user?.name} />
                           {/* <input type="text" className="input" value={user?.name } /> */}
                        </li>
                        <li className="min-w-60">
                           <Input title="E -posta" value={user?.email} />
                        </li>
                        <li className="min-w-60">
                           <Input
                              title="Kullanıcı adı"
                              value={user?.userName}
                           />
                        </li>
                     </ul>
                  </WidgetsPopup>
                  <ul className="flex justify-between">
                     <li className="min-w-60">
                        <p>İsim</p>
                        <b>{user?.name}</b>
                     </li>
                     <li className="min-w-60">
                        <p>E -posta</p>
                        <b>{user?.email}</b>
                     </li>
                     <li className="min-w-60">
                        <p>Kullanıcı adı</p>
                        <b>{user?.userName}</b>
                     </li>
                  </ul>
               </div>
               <div className="main relative">
                  <TagsInput tags={user?.tags} />
               </div>
               <div className="main relative">
                  {/* <WidgetsPopup title="Konum"> */}
                  <LocationInput user={user} userToken={userToken} />
                  {/* </WidgetsPopup> */}
                  {/* <b>{user?.location || "Konum belirtilmemiş"}</b> */}
               </div>
               <div className="main">
                  {/* <WidgetsPopup title="Telefon numarası"> */}
                  {/* <label className="w-full  flex items-center gap-4 "> */}
                  {/* <span className="bx bx-phone"></span> */}
                  <FormsPhoneNumber
                     placeholder="5xx xxx xxxx"
                     value={"5555555555"
                        .replace(/\D/g, "")
                        .replace(
                           /^(\d{1,3})(\d{0,3})(\d{0,4}).*/,
                           (m, g1, g2, g3) =>
                              [g1, g2, g3].filter(Boolean).join(" ")
                        )}
                  />
                  {/* </label> */}
                  {/* </WidgetsPopup> */}
                  {/* <label className="w-full  flex items-center gap-4 ">
                     <span className="bx bx-phone"></span>
                     {user?.phone}
                  </label> */}
               </div>
               <div className="main relative">
                  <WidgetsPopup title="Bio">
                     <textarea
                        className="w-full h-32 px-3 py-2 !bg-transparent border relative border-tertiary shadow shadow-tertiary rounded-2xl outline-none"
                        // value={user?.bio}
                        defaultValue={user?.bio || ""} // Use defaultValue for controlled component
                     >
                        {/* {user?.bio || "Kendinizden bahsedin..."} */}
                     </textarea>
                     <PrimaryBtn>Kaydet</PrimaryBtn>
                  </WidgetsPopup>
                  {/* <p className="">{user?.bio}</p> */}
                  {/* <SecondaryBtn className="ml-auto">Save</SecondaryBtn> */}
               </div>
               <div className="main relative">
                  <b className="py-2 inline-block">Social media</b>
                  <div className="flex items-center gap-2">
                     <label className="w-full  flex items-center gap-4 input">
                        <span className="bx bxl-facebook"></span>
                        <input
                           type="text"
                           className="w-full bg-transparent outline-none"
                           placeholder="Facebook"
                        />
                     </label>
                     <label className="w-full  flex items-center gap-4 input">
                        <span className="bx bxl-twitter"></span>
                        <input
                           type="text"
                           className="w-full bg-transparent outline-none"
                           placeholder="Twitter"
                        />
                     </label>
                     <label className="w-full  flex items-center gap-4 input">
                        <span className="bx bxl-instagram"></span>
                        <input
                           type="text"
                           className="w-full bg-transparent outline-none"
                           placeholder="Instagram"
                        />
                     </label>
                     <label className="w-full  flex items-center gap-4 input">
                        <span className="bx bxl-linkedin"></span>
                        <input
                           type="text"
                           className="w-full bg-transparent outline-none"
                           placeholder="LinkedIn"
                        />
                     </label>
                     <SecondaryBtn>Save</SecondaryBtn>
                  </div>
               </div>
            </main>
            <aside className="min-w-80 h-min main ">
               <h2 className="text-xl text-center">Profilinizi tamamlayın</h2>

               <ChartsDoughnut
                  datasets={[
                     {
                        label: "",
                        data: [
                           0,
                           Math.round(
                              (100 / userField.length) * validUserFieldCount
                           ) ?? 0,
                        ],
                        backgroundColor: ["rgba(0, 0, 0, .12)", "#d81f26"],
                        borderWidth: 1,
                     },
                  ]}
               />
               <ul className="">
                  {userField &&
                     userField.sort().map(([key, val]) => {
                        const isComplete =
                           val == null || val == undefined || val == ""
                              ? false
                              : true;
                        return (
                           <li
                              key={key}
                              className="py-2 flex items-center gap-2">
                              <i
                                 className={`bx ${
                                    isComplete
                                       ? "bx-check !text-green-500"
                                       : "bx-x"
                                 } text-2xl`}></i>
                              <span
                                 className={`${isComplete ? "font-bold" : ""}`}>
                                 {key.charAt(0).toUpperCase() +
                                    key
                                       .replace(/([A-Z])/g, " $1")
                                       .replace(/^./, (str) =>
                                          str.toUpperCase()
                                       )
                                       .slice(1)}
                              </span>
                              {/* <span>{user[key]}</span> */}
                           </li>
                        );
                     })}
               </ul>
            </aside>
         </section>
      </section>
   );
}
