"use client";

import { PrimaryBtn, SecondaryBtn } from "@/components/btn";

import { use, useEffect, useState } from "react";
import CompleteProfile from "@/components/widgets/profile/completeProfile";
// import FormsWebsite from "@/components/forms/website";

import { setAuthenticationUser } from "@/utils/auth";
import userContext from "@/components/provider/userContext";

import { AvatarImg, CoverImage } from "@/components/widgets/avatar";
import { putUserAvatar, putUserCoverPicture } from "@/services/user";
import AddressForm from "../../../../components/forms/address";
import FormsWebsite from "@/components/forms/websites";
import LocationInput from "@/components/forms/location";
import { resolveCoordinates } from "@/services/geoResolver";
import PrimaryFormButton from "@/components/forms/primaryBtn";

// export const metadata = {
//    title: " Emegen",
//    description: "Generated by create next app",
// };

export default function EditProfilePage() {
   const [user, setUser] = use(userContext);
   const [location, setLocation] = useState({
      latitude: user?.location?.latitude || null,
      longitude: user?.location?.longitude || null,
   });
   const [address, setAddress] = useState({});

   // console.log("file: edit-profile.jsx:13 => user=>", user);
   const [uploadingProfile, setUploadingProfile] = useState(false);
   const [uploadingCover, setUploadingCover] = useState(false);

   const handleFileUpload = async (e, type = "profilePicture") => {
      const file = e.target.files && e.target.files[0];
      if (!file) return;

      const fileSizeInMB = file.size / (1024 * 1024);
      if (fileSizeInMB > 5) {
         console.log("Dosya boyutu 5MB sınırını aşıyor.");
         e.target.value = "";
         return;
      }

      const formData = new FormData();
      formData.append("file", file);

      try {
         type === "profilePicture"
            ? setUploadingProfile(true)
            : setUploadingCover(true);
         const apiCall =
            type === "profilePicture" ? putUserAvatar : putUserCoverPicture;
         const response = await apiCall(formData);
         setUser({ ...response.data.user });
         setAuthenticationUser(response.data.user);
         e.target.value = "";
      } catch (error) {
         console.error("Güncelleme sırasında hata oluştu:", error);
      } finally {
         type === "profilePicture"
            ? setUploadingProfile(false)
            : setUploadingCover(false);
         e.target.value = "";
      }
   };

   const updatePersonalInformation = (data) => {
      // Implement the logic to update personal information
      console.log("Updating personal information with data:", data);
   };

   const handleWebsitesUpdated = (updatedWebsites) => {
      // merge into user context + auth storage so rest of app sees latest data
      const nextUser = { ...user, websites: updatedWebsites };
      setUser(nextUser);
      setAuthenticationUser(nextUser);
   };

   useEffect(() => {
      if (location.latitude && location.longitude) {
         resolveCoordinates({
            latitude: location.latitude,
            longitude: location.longitude,
         }).then(({ status, data: { address } }) => {
            if (status === 200) {
               setUser((prev) => ({
                  ...prev,
                  address: {
                     country: address.country || "",
                     city: address.province || "",
                     district: address.town || "",
                     streetAddress: `${address.road || ""}  ${
                        address.village
                     } Mah`.trim(),
                     zipCode: address.postcode || "",
                  },
               }));
            }
         });
      }
   }, [location.latitude, location.longitude]);

   return (
      <>
         <main className="flex-1">
            <h1 className="mb-4">Profili Düzenle</h1>
            <section className="flex flex-col gap-8">
               <div className="space-y-8">
                  {/* Kapak fotoğrafı kartı */}
                  <div className="main !p-0 relative  overflow-hidden ">
                     <div className="h-48 md:h-60 w-full bg-gray-100 dark:bg-zinc-800">
                        <CoverImage
                           src={user?.coverPicture}
                           alt="Kapak Fotoğrafı"
                        />
                     </div>
                     <label className="absolute top-3 right-3 inline-flex items-center gap-2 rounded-md bg-black/60 text-white px-3 py-1.5 text-sm hover:bg-black/70 cursor-pointer backdrop-blur">
                        <input
                           type="file"
                           className="sr-only"
                           accept="image/*"
                           onChange={(e) => handleFileUpload(e, "coverPicture")}
                        />
                        {uploadingCover
                           ? "Yükleniyor..."
                           : "Kapak fotoğrafını değiştir"}
                     </label>
                  </div>

                  {/* Profil fotoğrafı kartı */}
                  <div className="main">
                     <div className="flex items-center gap-4">
                        <div className="shrink-0">
                           <AvatarImg
                              src={user?.profilePicture || ""}
                              alt="Profil Fotoğrafı"
                           />
                        </div>
                        <div className="flex flex-col">
                           <span className="font-medium">Profil fotoğrafı</span>
                           <span className="text-sm text-gray-500 dark:text-gray-400">
                              En fazla 5MB, jpg/png
                           </span>
                           <div className="mt-2">
                              <label className="inline-flex items-center gap-2 rounded-md border px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-zinc-800">
                                 <input
                                    type="file"
                                    className="sr-only"
                                    accept="image/*"
                                    onChange={(e) =>
                                       handleFileUpload(e, "profilePicture")
                                    }
                                 />
                                 {uploadingProfile
                                    ? "Yükleniyor..."
                                    : "Yeni fotoğraf yükle"}
                              </label>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>

               <PrimaryFormButton />

               <div className="main">
                  {/* buisiness type */}
                  <div className="mb-4">
                     <label
                        htmlFor="businessType"
                        className="block mb-2 font-medium">
                        İşletme Türü
                     </label>
                     <select
                        id="businessType"
                        name="businessType"
                        defaultValue={user?.businessType || ""}
                        className="w-full text-black border border-gray-300 rounded-md p-2"
                        onChange={(e) =>
                           setUser((prev) => ({
                              ...prev,
                              businessType: e.target.value,
                           }))
                        }>
                        {[
                           "LocalBusiness",
                           "ConstructionBusiness", //
                           "HomeAndConstructionBusiness",
                           "ProfessionalService",
                           "Restaurant",
                           "CafeOrCoffeeShop",
                           "Bakery",
                           "FoodEstablishment",
                           "LegalService",
                           "AccountingService",
                           "RealEstateAgent",
                           "AutoRepair",
                           "AutoDealer",
                           "GasStation",
                           "Store",
                           "ClothingStore",
                           "ElectronicsStore",
                           "GroceryStore",
                           "GeneralContractor",
                           "Electrician",
                           "Plumber",
                           "HVACBusiness",
                           "Locksmith",
                           "CleaningService",
                           "MovingCompany",
                           "LandscapeService",
                           "HairSalon",
                           "BeautySalon",
                           "NailSalon",
                           "DaySpa",
                           "HealthClub",
                           "MedicalBusiness",
                           "Dentist",
                           "CafeOrCoffeeShop",
                           "BarOrPub",
                           "FastFoodRestaurant",
                           "Attorney",
                           "AccountingService",
                           "InsuranceAgency",
                           "AutoDealer",
                           "School",
                           "ChildCare",
                           "TravelAgency",
                           "PetStore",
                           "DryCleaningOrLaundry",
                        ].map((type, i) => (
                           <option
                              key={`buisiness-type${type}-${i}`}
                              value={type}>
                              {type}
                           </option>
                        ))}
                     </select>
                  </div>
               </div>

               <FormsWebsite
                  websites={user?.websites || {}}
                  onUpdated={handleWebsitesUpdated}
               />

               <LocationInput
                  onChange={(loc) => {
                     setLocation({
                        latitude: loc.lat,
                        longitude: loc.lng,
                     });
                  }}
               />

               <AddressForm
                  defaultValue={user?.address ?? {}}
                  placeholder="Konumunuzu girin"
               />
            </section>
         </main>
         <aside className="min-w-96 h-min">
            <CompleteProfile user={user} />
         </aside>
      </>
   );
}
