"use client";

import { PrimaryBtn, SecondaryBtn } from "@/components/btn";

import LocationInput from "../../../../components/forms/location";
import TagsInput from "@/components/forms/tags";
import { use, useEffect, useState } from "react";
import CompleteProfile from "@/components/widgets/profile/completeProfile";
import FormsWebsite from "@/components/forms/website";
import BiographyEditor from "@/components/forms/bio";

import { putUserAvatar } from "@/services/user";
import { setAuthenticationUser } from "@/utils/auth";
import userContext from "@/components/provider/userContext";

// export const metadata = {
//    title: " Emegen",
//    description: "Generated by create next app",
// };

export default function EditProfilePage() {
   const [user, setUser] = use(userContext);

   // console.log("file: edit-profile.jsx:13 => user=>", user);

   return (
      <>
         <main className="flex-1">
            <h1 className="mb-4">Edit profile</h1>
            <section className="flex flex-col gap-8">
               <div className="main flex flex-col gap-4">
                  <b>Kişisel Bilgiler</b>
                  <div className="flex flex-col gap-4">
                     <label>
                        <b className="py-2 block">İsim</b>
                        <input
                           className="w-full h-9 px-3 py-2 !bg-transparent border relative border-tertiary shadow shadow-tertiary rounded-2xl outline-none"
                           type="text"
                           defaultValue={user?.name || ""}
                           placeholder="İsminizi girin"
                        />
                     </label>
                     <label>
                        <b className="py-2 block">Kullanıcı Adı</b>
                        <input
                           className="w-full h-9 px-3 py-2 !bg-transparent border relative border-tertiary shadow shadow-tertiary rounded-2xl outline-none"
                           type="text"
                           defaultValue={user?.userName || ""}
                           placeholder="Kullanıcı adınızı girin"
                        />
                     </label>
                  </div>
                  <SecondaryBtn className="ml-auto">Güncelle</SecondaryBtn>
               </div>
               <BiographyEditor defaultValue={user?.bio} />
               <LocationInput
                  defaultValue={user?.location || ""}
                  placeholder="Konumunuzu girin"
                  onChange={(e) => {
                     console.log("Location changed:", e);
                  }}
               />
                  <TagsInput
                     tags={user?.tags}
                     placeholder="İlgi alanlarınızı girin"
                     onChange={(e) => {
                        console.log("Tags changed:", e);
                     }}
                  />
            </section>
         </main>
         <aside className="min-w-80 h-min">
            <CompleteProfile user={user} />
         </aside>
      </>
   );
}
